### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by eeriemyxi** [Kirigod/ssl-verifier#1]
This module is working fine on my computer but when I ran my code on repl.it, it gave me errors, 
```
/home/runner/URL-Shortener/node_modules/ssl-verifier/index.js:63
                if(input?.method) output.method = input.method;
                         ^

SyntaxError: Unexpected token '.'
```

**Comment by Kirigod** [comment]
Hello! maybe something related to the NodeJs version? make sure you are using at least version **14.16.1**, this package (v1.0.0) was produced in this version, so there is no guarantee that it will work perfectly on older versions :)

**Comment by Kirigod** [comment]
Since I haven't received any more responses, I think the issue has been resolved, so I will close this issue.

**Comment by eeriemyxi** [comment]
Sorry for late reply but, I used another module that did the job well.

**Comment by Kirigod** [comment]
Great! unfortunately this module won't work well on previous versions of nodejs :/
